export interface BlogPost {
  id: string;
  slug: string;
  title: string;
  category: 'Tech' | 'Flutter' | 'Android' | 'Career' | 'Life';
  tags: string[];
  content: string;
  excerpt: string;
  publishedAt: string;
  readTime: number;
  coverColor: string;
}

export const BLOG_CATEGORIES = ['All', 'Tech', 'Flutter', 'Android', 'Career', 'Life'] as const;

const sampleBlog: BlogPost[] = [
  {
    id: '1',
    slug: 'flutter-vs-android-native-2024',
    title: 'Flutter vs Native Android in 2024: A Developer\'s Real-World Take',
    category: 'Flutter',
    tags: ['Flutter', 'Android', 'Kotlin', 'Performance'],
    excerpt: 'After building production apps in both ecosystems, here\'s my honest comparison of Flutter and native Android development.',
    publishedAt: '2024-11-10',
    readTime: 8,
    coverColor: 'linear-gradient(135deg, #06b6d4, #6366f1)',
    content: `# Flutter vs Native Android in 2024

After spending years shipping production apps in both Flutter and native Android (Kotlin), I've gathered real-world insights that go beyond benchmarks.

## The Performance Question

The biggest misconception is that native is always faster. In practice, Flutter's Skia/Impeller rendering engine is **incredibly smooth** — 60fps on budget devices that would struggle with complex native UIs.

\`\`\`dart
// Flutter's widget tree rebuilds are surgical
Widget build(BuildContext context) {
  return AnimatedContainer(
    duration: const Duration(milliseconds: 300),
    child: const MyWidget(),
  );
}
\`\`\`

## Where Native Still Wins

- **Deep OS integrations**: Custom camera pipelines, background services
- **Platform-specific UI**: When you need pixel-perfect iOS/Android feel
- **Complex Bluetooth/NFC**: Native SDKs integrate seamlessly

## The Verdict

For 90% of business apps, Flutter wins on speed of delivery, code sharing, and maintenance cost. For system-level apps, go native.

---

*What's your experience? I'd love to hear from the community.*`
  },
  {
    id: '2',
    slug: 'ai-in-mobile-development',
    title: 'How I Use AI Tools to 10x My Mobile Development Speed',
    category: 'Tech',
    tags: ['AI', 'ChatGPT', 'Claude', 'Productivity'],
    excerpt: 'From boilerplate generation to code reviews — the AI workflow that transformed how I ship features.',
    publishedAt: '2024-10-22',
    readTime: 6,
    coverColor: 'linear-gradient(135deg, #a855f7, #6366f1)',
    content: `# How I Use AI Tools to 10x My Mobile Development Speed

The developer who ignores AI tooling in 2024 is the developer who ignores Stack Overflow in 2014. Here's my actual workflow.

## My AI Stack

1. **Claude** — Architecture decisions and complex refactors
2. **ChatGPT** — Quick code snippets and docs lookup
3. **GitHub Copilot** — Line-by-line autocomplete

## Real Examples from My Workflow

### Boilerplate Generation
What used to take 2 hours of scaffolding now takes 10 minutes. I prompt Claude with my data model and get a full repository pattern implementation.

\`\`\`kotlin
// Generated by AI, reviewed by me:
class UserRepository @Inject constructor(
    private val api: ApiService,
    private val dao: UserDao
) {
    fun getUsers(): Flow<Resource<List<User>>> = flow {
        emit(Resource.Loading())
        // ... full implementation
    }
}
\`\`\`

### Code Review Partner
Before every PR, I paste my diff into Claude and ask: *"What edge cases am I missing?"* It catches things reviewers skip.

## The Mindset Shift

AI doesn't replace understanding — it amplifies it. You still need to know why the code works.`
  },
  {
    id: '3',
    slug: 'from-freelance-to-product-company',
    title: 'Lessons from 3 Years of Freelancing Before Joining a Product Company',
    category: 'Career',
    tags: ['Freelance', 'Career', 'Growth', 'Lessons'],
    excerpt: 'What 3 years of client work taught me that no boot camp ever could — and what I\'d do differently.',
    publishedAt: '2024-09-15',
    readTime: 5,
    coverColor: 'linear-gradient(135deg, #f59e0b, #ef4444)',
    content: `# Lessons from 3 Years of Freelancing

From May 2018 to June 2021, I ran my own small dev practice — building Android apps and WordPress sites for clients across India and abroad. Here's what I actually learned.

## The Good

**You learn to ship.** With client deadlines and real money on the line, you stop being a perfectionist and start being a problem solver.

**Breadth of experience.** In one year, I touched healthcare, logistics, e-commerce, and education apps. Junior devs at big companies often work on one domain for years.

## The Hard Lessons

### Communication is the real product
The best technical solution means nothing if the client doesn't trust you. I lost a contract because I went silent for 3 days while debugging a tricky API issue. Never again.

### Scope creep kills margins
Always get change requests in writing. "Can you just add one more thing?" is the sentence that destroys project profitability.

## Making the Leap to a Product Company

When I joined Airan Limited in 2021, the biggest adjustment was **patience**. Freelancing rewires you for immediate feedback. Enterprise timelines are different.

> The best career move is to embrace wherever you are fully, then grow deliberately.`
  }
];

const STORAGE_KEY = 'jigish_blog_posts';

export function getBlogPosts(): BlogPost[] {
  try {
    const stored = localStorage.getItem(STORAGE_KEY);
    if (stored) {
      const parsed = JSON.parse(stored) as BlogPost[];
      if (parsed.length > 0) return parsed;
    }
  } catch {}
  return sampleBlog;
}

export function saveBlogPosts(posts: BlogPost[]): void {
  localStorage.setItem(STORAGE_KEY, JSON.stringify(posts));
}

export function getBlogPost(slug: string): BlogPost | undefined {
  return getBlogPosts().find(p => p.slug === slug);
}

export function generateSlug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .trim();
}
